[workspace]
name = "finch-tensor-lite"
version = "0.1.0"
description = "Sparse And Structured Tensor Programming"
authors = ["Willow Ahrens <willow.marie.ahrens@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]
requires-pixi = ">=0.71.0"

[environments]
test = { features = ["test"], solve-group = "default" }
mindeps = { features = ["test", "mindeps"], solve-group = "default" }
pre-commit = { features = ["pre-commit"], no-default-feature = true }

# finch-tensor-lite package definition #

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
ignore-pypi-mapping = false

# default feature definition #

[dependencies]
finch-tensor-lite.path = "."

[dev]
# pulls in host and run dependencies
finch-tensor-lite.path = "."

[tasks]
compile = "python -c 'import finchlite'"

# non-default feature definitions #

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
sparse = "*"
scipy = "*"
mypy = "*"
pytest-mypy = "*"
pytest-regressions = "*"

[feature.test.tasks.test]
cmd = "pytest"
depends-on = ["compile"]
default-environment = "test"

[feature.test.tasks.type-check]
cmd = "mypy ."
default-environment = "test"

[feature.mindeps.dependencies]
python = "3.11.*"

[feature.pre-commit.dependencies]
pre-commit = "*"

[feature.pre-commit.tasks]
pre-commit-install = "pre-commit install"
pre-commit = "pre-commit run -a"
