from .tensor_stats import TensorStats


class DatabaseStat(TensorStats):
    def __init__(): ...

    @staticmethod
    def aggregate(): ...
    @staticmethod
    def mapjoin(): ...

    @staticmethod
    def issimilar(): ...

    @staticmethod
    def relabel(): ...

    @staticmethod
    def reorder(): ...

    @staticmethod
    def copy_stats(): ...

    def estimate_non_fill_values(): ...
