name: Benchmark
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.71.3
          environments: benchmark
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime,memory
          run: |
            pixi run -e benchmark pytest benchmarks/ --codspeed -vvv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
