name: Benchmark
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
      - name: Configure poetry
        run: |
          poetry env use python3.12
      - name: Install package
        run: |
          poetry install --extras benchmark
      - name: Run time benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: pytest benchmarks/ --codspeed


      - name: Run memory benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: memory
          run: pytest benchmarks/ --codspeed

on:
  pull_request:
    branches:
      - main
